jobs:
  include:
    - stage: test
      language: java
      jdk: oraclejdk8
      before_install:
      - if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "[skip travis test]" ; then echo "skipping travis test" && exit 0 ; fi
      - git config --global user.email "builds@travis-ci.com"
      - git config --global user.name "Travis CI"
      - pushd ~/build/
      - git clone https://github.com/NyaaCat/NyaaCore NyaaCat/NyaaCore
      - pushd ./NyaaCat/NyaaCore
      - git checkout -qf 2f279c948020469115537e4f71e149c8143ea047
      - popd
      - git clone https://github.com/NyaaCat/nyaautils NyaaCat/nyaautils
      - pushd ./NyaaCat/nyaautils
      - git checkout -qf cb6576de85d0eaa4302ce85862962ea054b9e41c
      - popd
      - export NYAACORE_LANG_DIR=`readlink -f ./NyaaCat/NyaaCore/src/main/resources/lang/`
      - popd
      install: true
      before_script: ./gradlew build
      script:
      - export BUILT_JAR=`readlink -f ./build/libs/NyaaUtilsLangChecker.jar`
      - export PATCH_DIR=`readlink -f ./src/test/resources/`
      - echo $BUILT_JAR
      - echo $PATCH_DIR
      - pushd ~/build/
      - pushd ./NyaaCat/nyaautils
      - git apply $PATCH_DIR/nu-cb6576d.txt
      - mkdir -p lib/
      - cp $BUILT_JAR ./lib/NyaaUtilsLangChecker.jar
      - gradle assemble --stacktrace 2>&1 | tee build.log
      - grep "lc_test1" build.log
      - grep "lc_test2" build.log
      - grep "lc_test3" build.log
      - grep "lc_test4" build.log
      - grep "lc_test5" build.log
      - grep "lc_test6" build.log
      - popd
      - pushd ./NyaaCat/NyaaCore
      - git apply $PATCH_DIR/nc-2f279c9.txt
      - mkdir -p lib/
      - cp $BUILT_JAR ./lib/NyaaUtilsLangChecker.jar
      - gradle assemble  --stacktrace 2>&1 | tee build.log
      - grep "lc_test1" build.log
      - grep "lc_test2" build.log
      - grep "lc_test3" build.log
      - grep "lc_test4" build.log
      - grep "lc_test5" build.log
      - grep "lc_test6" build.log
      - popd
      - popd
      env:
        - JAVAC_OPTS='-ALANG_SHOW_DEBUG=true'
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -f  $HOME/.gradle/caches/4.1/fileHashes/fileHashes.bin
        - rm -f  $HOME/.gradle/caches/4.1/fileHashes/fileHashes.lock
        - rm -f  $HOME/.gradle/caches/transforms-1/transforms-1.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
    - stage: test
      language: java
      sudo: false
      dist: trusty
      jdk: oraclejdk9
      before_install:
      - if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "[skip travis test]" ; then echo "skipping travis test" && exit 0 ; fi
      - git config --global user.email "builds@travis-ci.com"
      - git config --global user.name "Travis CI"
      - pushd ~/build/
      - git clone https://github.com/NyaaCat/NyaaCore NyaaCat/NyaaCore
      - pushd ./NyaaCat/NyaaCore
      - git checkout -qf 2f279c948020469115537e4f71e149c8143ea047
      - popd
      - git clone https://github.com/NyaaCat/nyaautils NyaaCat/nyaautils
      - pushd ./NyaaCat/nyaautils
      - git checkout -qf cb6576de85d0eaa4302ce85862962ea054b9e41c
      - popd
      - export NYAACORE_LANG_DIR=`readlink -f ./NyaaCat/NyaaCore/src/main/resources/lang/`
      - popd
      install: true
      before_script: ./gradlew build
      script:
      - export BUILT_JAR=`readlink -f ./build/libs/NyaaUtilsLangChecker.jar`
      - export PATCH_DIR=`readlink -f ./src/test/resources/`
      - export GRADLEW_LC=`readlink -f ./gradle/`
      - export GRADLEW_SH_LC=`readlink -f ./gradlew`
      - echo $BUILT_JAR
      - echo $PATCH_DIR
      - echo $GRADLEW_LC
      - echo $GRADLEW_SH_LC
      - pushd ~/build/
      - pushd ./NyaaCat/nyaautils
      - git apply $PATCH_DIR/nu-cb6576d.txt
      - mkdir -p lib/
      - cp $BUILT_JAR ./lib/NyaaUtilsLangChecker.jar
      - cp -R $GRADLEW_LC .
      - cp $GRADLEW_SH_LC .
      - ./gradlew assemble  --stacktrace 2>&1 | tee build.log
      - grep "lc_test1" build.log
      - grep "lc_test2" build.log
      - grep "lc_test3" build.log
      - grep "lc_test4" build.log
      - grep "lc_test5" build.log
      - grep "lc_test6" build.log
      - popd
      - pushd ./NyaaCat/NyaaCore
      - git apply $PATCH_DIR/nc-2f279c9.txt
      - mkdir -p lib/
      - cp $BUILT_JAR ./lib/NyaaUtilsLangChecker.jar
      - cp -R $GRADLEW_LC .
      - cp $GRADLEW_SH_LC .
      - ./gradlew assemble --stacktrace 2>&1 | tee build.log
      - grep "lc_test1" build.log
      - grep "lc_test2" build.log
      - grep "lc_test3" build.log
      - grep "lc_test4" build.log
      - grep "lc_test5" build.log
      - grep "lc_test6" build.log
      - popd
      - popd
      env:
        - JAVAC_OPTS='-ALANG_SHOW_DEBUG=true'
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -f  $HOME/.gradle/caches/4.1/fileHashes/fileHashes.bin
        - rm -f  $HOME/.gradle/caches/4.1/fileHashes/fileHashes.lock
        - rm -f  $HOME/.gradle/caches/transforms-1/transforms-1.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
    - stage: deploy
      language: java
      jdk: oraclejdk8
      before_install:
      - if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "[skip travis deploy]" ; then echo "skipping travis deploy" && exit 0 ; fi
      - git config --global user.email "builds@travis-ci.com"
      - git config --global user.name "Travis CI"
      after_success:
      - 'cp build/libs/NyaaUtilsLangChecker.jar ./NyaaUtilsLangChecker-$TRAVIS_BRANCH-v$main_version.$TRAVIS_BUILD_NUMBER.jar'
      before_deploy:
      - export GIT_TAG=$TRAVIS_BRANCH-v$main_version.$TRAVIS_BUILD_NUMBER
      - export GIT_ORIGIN_URL=`git config --get remote.origin.url`
      - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
      - git config credential.helper "store --file=.git/credentials"
      - echo "https://$GITHUB_KEY:@github.com" > .git/credentials
      - git push origin HEAD:$TRAVIS_BRANCH -q --follow-tags
      - gem install octokit -v 4.3.0
      - ./gradlew publish
      - cd ..
      - git clone -b maven-repo $GIT_ORIGIN_URL NyaaUtilsLangChecker-mvn
      - cp -r NyaaUtilsLangChecker/build/repo/org NyaaUtilsLangChecker-mvn/
      - cd NyaaUtilsLangChecker-mvn
      - git config credential.helper "store --file=.git/credentials"
      - echo "https://$GITHUB_KEY:@github.com" > .git/credentials
      - git add .
      - git commit -m "auto generated maven repo"
      - git push --follow-tags
      - cd ../NyaaUtilsLangChecker
      deploy:
      - provider: releases
        skip_cleanup: true
        prerelease: true
        api_key: ${GITHUB_DEPLOY_KEY}
        file: './NyaaUtilsLangChecker-$TRAVIS_BRANCH-v$main_version.$TRAVIS_BUILD_NUMBER.jar'
        on:
          tags: false
          all_branches: true
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -f  $HOME/.gradle/caches/4.1/fileHashes/fileHashes.bin
        - rm -f  $HOME/.gradle/caches/4.1/fileHashes/fileHashes.lock
        - rm -f  $HOME/.gradle/caches/transforms-1/transforms-1.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
env:
  global:
    - main_version=1
branches:
  except:
  - "/^*-v[0-9]/"
  - "maven-repo"